# Generated by Django 6.0.1 on 2026-04-28 21:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegislativeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('vote', 'Votación'), ('hearing', 'Audiencia'), ('committee', 'Comité'), ('debate', 'Debate'), ('other', 'Otro')], db_index=True, default='other', max_length=50)),
                ('date', models.DateTimeField(db_index=True)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('participants', models.JSONField(blank=True, default=list)),
                ('outcome', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evento Legislativo',
                'verbose_name_plural': 'Eventos Legislativos',
                'ordering': ['-date'],
            },
        ),
    ]
