# Generated by Django 6.0.1 on 2026-04-28 21:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('source', models.CharField(db_index=True, max_length=200)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('country', models.CharField(db_index=True, max_length=10)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artículo de Noticias',
                'verbose_name_plural': 'Artículos de Noticias',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('human_rights_impact', models.FloatField(default=0)),
                ('democratic_impact', models.FloatField(default=0)),
                ('sentiment', models.CharField(blank=True, max_length=50)),
                ('key_concerns', models.JSONField(blank=True, default=list)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('llamaparse_response', models.JSONField(blank=True, default=dict)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='news.newsarticle')),
            ],
            options={
                'verbose_name': 'Análisis de Noticias',
                'verbose_name_plural': 'Análisis de Noticias',
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
