# Generated by Django 6.0.1 on 2026-04-28 21:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('law', 'Ley'), ('news', 'Noticia'), ('event', 'Evento')], max_length=20)),
                ('content_id', models.UUIDField()),
                ('human_rights_score', models.FloatField(default=0)),
                ('democratic_score', models.FloatField(default=0)),
                ('violations_detected', models.JSONField(blank=True, default=list)),
                ('concerns', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('llamaparse_response', models.JSONField(blank=True, default=dict)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Análisis de Contenido',
                'verbose_name_plural': 'Análisis de Contenidos',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='DemocraticParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('weight', models.FloatField(default=1.0)),
                ('category', models.CharField(choices=[('participation', 'Participación'), ('accountability', 'Rendición de cuentas'), ('transparency', 'Transparencia')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Parámetro Democrático',
                'verbose_name_plural': 'Parámetros Democráticos',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HumanRightsParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('weight', models.FloatField(default=1.0)),
                ('category', models.CharField(choices=[('civil', 'Civil'), ('political', 'Político'), ('economic', 'Económico'), ('social', 'Social')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Parámetro de Derechos Humanos',
                'verbose_name_plural': 'Parámetros de Derechos Humanos',
                'ordering': ['category', 'name'],
            },
        ),
    ]
