# Generated by Django 6.0.1 on 2026-04-28 21:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True)),
                ('full_text', models.TextField(blank=True)),
                ('law_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('jurisdiction', models.CharField(db_index=True, max_length=100)),
                ('publication_date', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('source_api', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('repealed', 'Derogado')], db_index=True, default='published', max_length=20)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ley',
                'verbose_name_plural': 'Leyes',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='LawAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('human_rights_score', models.FloatField(default=0)),
                ('democratic_score', models.FloatField(default=0)),
                ('concerns', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('llamaparse_response', models.JSONField(blank=True, default=dict)),
                ('law', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='legislation.law')),
            ],
            options={
                'verbose_name': 'Análisis de Ley',
                'verbose_name_plural': 'Análisis de Leyes',
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
